### ISSUE TITLE
Code available?

### ISSUE THREAD

**Issue by DavidePaglieri** [danielism97/ST-MFNet#1]
Hello, are you still planning to publish the inference/training code of your paper? Thanks!

**Comment by danier97** [comment]
Hi Davide, thank you for your interest! I will try to upload the inference code today.

**Comment by hiredd** [comment]
will you plan to upload the trainning code？ @danielism97

**Comment by danier97** [comment]
Hi, I will upload training code as soon as possible. Apologies for the delay.

**Comment by hiredd** [comment]
good job

**Comment by danier97** [comment]
Hi, the training code has been uploaded.

Many thanks.
