### ISSUE TITLE
BVI-DVC quintuplets

### ISSUE THREAD

**Issue by JHLew** [danielism97/ST-MFNet#11]
Hi, I was going through your work recently, and figured that the link to the BVI-DVC quintuplets has been expired.
I wish to have access to the link, but it seems to be broken.

Could you kindly check and make it available it again?

**Comment by danier97** [comment]
Hi, apologies for the inconvenience. It should work now.

**Comment by JHLew** [comment]
Thank you for the quick response!

**Comment by JHLew** [comment]
Hi, seems like the link to VFITex is also broken.
Could you check this out too?

**Comment by danier97** [comment]
That's also been fixed now.
