### ISSUE TITLE
Right YUV format of the input video?

### ISSUE THREAD

**Issue by ichlubna** [danielism97/ST-MFNet#12]
Hello,
I would like to ask how exactly should we encode the input video.
I have a directory with PNG frames. I did simply:
```
ffmpeg -i myDir/%02d.png -pix_fmt yuv444p test444.yuv
python interpolate_yuv.py --net STMFNet --checkpoint stmfnet.pth --yuv_path test444.yuv --size 3840x2160 --out_fps 30 --out_dir test --batch_size 4 --patch_size 256 --overlap 4
ffmpeg -i test/test.yuv_3840x2160_30fps_STMFNet.mp4 -video_size 3840x2160 -framerate 30 test/%04d.png
```
Everything works but the results are strange with distorted colors. I believe that there is a mismatch between the used YUV formats. Would you please share your commands for the correct processing?
Thanks!

**Comment by danier97** [comment]
Hi,

I've run the exact same commands as yours, and the results look fine to me. Could you please 

1. double check if the intermediate yuv outputs are as expected. You can view YUV files with [YUView](https://ient.github.io/YUView/).
2. share examples of the strange outputs.

Many thanks.

**Comment by ichlubna** [comment]
Thank you for your quick reply. I used YUView to check the results.
The first conversion with ffmpeg seems to be OK. After experimenting I noticed, that the problem was maybe that I used too few frames. I wanted to try a simple interpolation between two frames which seems to be not enough, having just two-framed video. Is that right?
After adding more, I can see some results.

**Comment by danier97** [comment]
Yes that is correct - at least 4 frames are required for this method.

**Comment by ichlubna** [comment]
Alright, many thanks!
