### ISSUE TITLE
vfitex dataset is not complete 

### ISSUE THREAD

**Issue by FR6024** [danielism97/ST-MFNet#16]
Hello, thank you very much for sharing the code and dataset. After downloading the vfitex dataset, I found that in vfitex --->sakura_4K_pexels. There are only 87 photos in the  folder, while the other files have 100 photos below, so when running the code, only 934 quintuplets can be read instead of the 940 mentioned in the paper

**Comment by danier97** [comment]
Hi,

I've checked the dataset on my end and it appears that the sakura sequence indeed contains only 87 photos. So it should be a typo in the paper. Apologies for the confusion.

Many thanks.

**Comment by FR6024** [comment]
> Hi,
> 
> I've checked the dataset on my end and it appears that the sakura sequence indeed contains only 87 photos. So it should be a typo in the paper. Apologies for the confusion.
> 
> Many thanks.

Thank you for your reply! I have run your test  and the results are correct. Thank you again for your open source and outstanding contributions！！！

**Comment by danier97** [comment]
Thank you very much for your kind words and your interest in our work!
