### ISSUE TITLE
What does the "getattr" mean in the stmfnet.py? I didn't find its definition

### ISSUE THREAD

**Issue by wong00** [danielism97/ST-MFNet#2]
`self.feature_extractor = getattr(feature, args.featnet)(args.featc, norm_layer=args.featnorm)`

**Comment by danier97** [comment]
Hi there,

`getattr()` is a Python built-in function for obtaining attributes of objects. You can learn more [here](https://stackoverflow.com/questions/4075190/what-is-getattr-exactly-and-how-do-i-use-it).

What this line of code does is to instantiate the feature extraction network (defined in `models/feature.py`) according to `args.featnet`. For example, if `args.featnet` is `'UMultiScaleResNext'`, then this is equivalent to the following.
`self.feature_extractor = feature.UMultiScaleResNext(args.featc, norm_layer=args.featnorm)`

Thanks.

**Comment by wong00** [comment]
> Hi there,
> 
> `getattr()` is a Python built-in function for obtaining attributes of objects. You can learn more [here](https://stackoverflow.com/questions/4075190/what-is-getattr-exactly-and-how-do-i-use-it).
> 
> What this line of code does is to instantiate the feature extraction network (defined in `models/feature.py`) according to `args.featnet`. For example, if `args.featnet` is `'UMultiScaleResNext'`, then this is equivalent to the following. `self.feature_extractor = feature.UMultiScaleResNext(args.featc, norm_layer=args.featnorm)`
> 
> Thanks.

Thanks a lot for your answer!

**Comment by wong00** [comment]
> Hi there,
> 
> `getattr()` is a Python built-in function for obtaining attributes of objects. You can learn more [here](https://stackoverflow.com/questions/4075190/what-is-getattr-exactly-and-how-do-i-use-it).
> 
> What this line of code does is to instantiate the feature extraction network (defined in `models/feature.py`) according to `args.featnet`. For example, if `args.featnet` is `'UMultiScaleResNext'`, then this is equivalent to the following. `self.feature_extractor = feature.UMultiScaleResNext(args.featc, norm_layer=args.featnorm)`
> 
> Thanks.

Thanks a lot for your answer!
