### ISSUE TITLE
Retrain using existing Trained model 

### ISSUE THREAD

**Issue by harshitha-lab** [danielism97/ST-MFNet#6]
Hello, 

I'm trying to retrain the model with my own dataset. I want to use existing model a the bae checkpoint to start the training.. 

I downloaded the pretrained model- stmfnet.pth 
when I passed - 
python train.py --net STMFNet --data_dir G:\WorkSpace\Harshitha\ST-MFNet-main --out_dir ./train_resultswithO --epochs 100 --batch_size 4 --loss 1*Lap --patch_size 256 --lr 0.001 --decay_type plateau --gamma 0.5 --patience 5 --optimizer ADAMax --load stmfnet.pth 

in train.py 
we have - start_epoch = checkpoint['epoch'] in line 79 .. 

I'm getting an error - 
KeyError: 'epoch'

.. 
could you please help me out.. .pth file does not have epoch

**Comment by danier97** [comment]
Hi, thank you for your interest in our work! You can add the 'epoch' key to the checkpoint dictionary by doing something like this:
```
ckpt = torch.load('stmfnet.pth')
ckpt['epoch'] = 70 # the model has been trained for 70 epochs
torch.save(ckpt, 'stmfnet_new.pth')
```
Then use the newly saved checkpoint file.

Thanks.

**Comment by harshitha-lab** [comment]
Thank You so much.. I'm able to retrain
