### ISSUE TITLE
VFITex dataset is not available.

### ISSUE THREAD

**Issue by Juns1105** [danielism97/ST-MFNet#7]
Hi, 

First of all, thank you so much for your well-developed research of VFI.
I'm raising an issue because I can't access your VFITex dataset.
When I try to download it, the message pops up and says "the link has expired".
Can I access your VFITex?

Thank you!

**Comment by danier97** [comment]
Hi, 

Thank you very much for your kind words, and apologies for the inconvenience. I have updated the link and you should now be able to access it.

Many thanks.

**Comment by Juns1105** [comment]
> Hi,
> 
> Thank you very much for your kind words, and apologies for the inconvenience. I have updated the link and you should now be able to access it.
> 
> Many thanks.

Thanks for your quick answer and fix!
