### ISSUE TITLE
4x or 8x interpolation?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [danielism97/ST-MFNet#9]
Thanks for sharing this great work!

Does interpolate_yuv.py only allow for a 2x interpolation?   How can I do a 4x or 8x interpolation?

**Comment by danier97** [comment]
Hi, sorry for the late reply and thank you for your interest in our work. Yes the script you mentioned only does x2 interpolation. We did x4 and x8 interpolation in this paper by applying the method recursively (i.e. do x2 first, then do x4 on the x2 result). 

Thanks.

**Comment by noobtoob4lyfe** [comment]
Thanks for the response!
